"""game_retention

Revision ID: eab503b3e51b
Revises: 12c29568e213
Create Date: 2026-06-13 18:58:15.800922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab503b3e51b'
down_revision: Union[str, Sequence[str], None] = '12c29568e213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_limit', sa.Integer(), nullable=False),
    sa.Column('current_limit_enabled', sa.Boolean(), nullable=False),
    sa.Column('finished_limit', sa.Integer(), nullable=False),
    sa.Column('finished_limit_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('games', sa.Column('favorite', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('games', sa.Column('finished_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'finished_at')
    op.drop_column('games', 'favorite')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
